"""Class for representing photometric data."""

from . import struct

Photometry = struct._Photometry
# PHOTOMETRY = Photometry.keychain
PHOTOMETRY = Photometry._KEYCHAIN
Photometry._KEYS = PHOTOMETRY

# NOTE: temporary fix LZK
PHOTOMETRY.FLUX_DENSITY = PHOTOMETRY.FLUXDENSITY
PHOTOMETRY.U_FLUX_DENSITY = PHOTOMETRY.U_FLUXDENSITY
PHOTOMETRY.E_FLUX_DENSITY = PHOTOMETRY.E_FLUXDENSITY

PHOTOMETRY.COUNT_RATE = PHOTOMETRY.COUNTRATE
PHOTOMETRY.E_COUNT_RATE = PHOTOMETRY.E_COUNTRATE
PHOTOMETRY.U_COUNT_RATE = PHOTOMETRY.U_COUNTRATE

PHOTOMETRY.UPPER_LIMIT = PHOTOMETRY.UPPERLIMIT
PHOTOMETRY.LOWER_LIMIT = PHOTOMETRY.LOWERLIMIT

PHOTOMETRY.PHOTON_INDEX = PHOTOMETRY.PHOTONINDEX

PHOTOMETRY.UNABSORBED_FLUX = PHOTOMETRY.UNABSORBEDFLUX
PHOTOMETRY.E_UNABSORBED_FLUX = PHOTOMETRY.E_UNABSORBEDFLUX
PHOTOMETRY.E_UPPER_UNABSORBED_FLUX = PHOTOMETRY.E_UPPER_UNABSORBEDFLUX
PHOTOMETRY.E_LOWER_UNABSORBED_FLUX = PHOTOMETRY.E_LOWER_UNABSORBEDFLUX

PHOTOMETRY.BAND_SET = PHOTOMETRY.BANDSET
